In this notebook i have covered the most fundametnal concepts of tensors using tensorflow

Introduction to tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#creating tensors with tf constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#number of dimensions of tensor
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
vector3 = tf.constant([[10,7],[7,10]])
vector3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
vector3.ndim

2

In [8]:
vector2 = tf.constant([[[10],[7]],[[7],[10]]])
vector2

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [9]:
vector2.ndim

3

Scalar: Typically a single number 

Vector: typically number with a direction

Matrix: is typically a multidimensional array of numbers however here we consider it wo have only two dimensions required for description which is typically a row and a column

Tensor: sort of like a matrix but is actually an n-dimesnional where n can be any number from 0 to infininty and all of the above mentioned types are forms of n-dimensional tensors

In [10]:
#creating variables using tf.variable instead of constant

In [11]:
change_tensor = tf.Variable([23,7])
unchange_tensor = tf.constant([23,7])
change_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([23,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([23,  7], dtype=int32)>)

In [12]:
# manipulating the elements in the tensor

In [13]:
change_tensor[0].assign(2002)
change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2002,    7], dtype=int32)>

In [14]:
# unchange_tensor[0].assign(2002)
# since the declaration of the tensor here is supposed to be unchnagable type it does not
# contain any attribute to change or to modify the value that has been assigned tio the tensor


Random tensors are tensors of some arbitrary size which contain random numbers

In [15]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape = (3,2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3,2))

random1,random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

In [16]:
random3 = tf.random.Generator.from_seed(42)
random3 = random3.uniform(shape = (3,2))
random4 = tf.random.Generator.from_seed(42)
random4 = random4.uniform(shape = (3,2))

random3,random4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>)

In [17]:
tf.random.shuffle(vector2,seed = 42)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [18]:
tf.ones([3,3],tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [19]:
tf.zeros([3,5],tf.int32)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

Turn numpy array into tensors
the main difference between numpy arrays and tensors is that tensors can be run on GPU for better computing

In [20]:
import numpy as np
numpy_a = np.arange(1,25,dtype = np.int32)

#capital value of a variable name is typically used in cases where we Re specifying matrix or tensors
#whereas we typically use specification of smaller letters to use in the case of vectors

In [21]:
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
tensor_A = tf.constant(numpy_a, shape = (2,3,4))
tensor_A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

gettin informattion and attributes of the tenosrs being used

In [23]:
tensor_B = tf.constant([[[[1,2,3,4],
                          [1,2,3,4]],
                         [[2,3,4,5],
                         [2,3,4,5]]]])

tensor_B

<tf.Tensor: shape=(1, 2, 2, 4), dtype=int32, numpy=
array([[[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[2, 3, 4, 5],
         [2, 3, 4, 5]]]], dtype=int32)>

In [24]:
# this is just to test whether the runtime is connected or not
print("Hello World")

Hello World


In [25]:
tensor_5 = tf.constant([[10,7],[3,4]])
tensor_5 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [26]:
tf.add(tensor_5,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [27]:
# performing matrox multiplication on tneosrs in tf
tfmul1 = tf.constant([[10,7],
                      [7,10]])
tfmul2 = tf.constant([[1,1],
                      [1,1]])
tf.matmul(tfmul1,tfmul2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 17],
       [17, 17]], dtype=int32)>

In [28]:
tfmul3 = tf.constant([[[1,2,5],
                       [7,2,1],
                       [3,3,3]]])

tfmul4 = tf.constant([[3,5],
                      [6,7],
                      [1,8]])

tf.matmul(tfmul3,tfmul4)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [29]:
tfmul3 @ tfmul3

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[30, 21, 22],
        [24, 21, 40],
        [33, 21, 27]]], dtype=int32)>

In [30]:
tfmul3 @ tfmul4

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [31]:
# the dot product

In [32]:
tf.tensordot(tfmul3,tfmul4,axes = 1)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [33]:
tfct = tf.constant([[10,20],[20,30]])
tfct.dtype

tf.int32

In [34]:
tfct2 = tf.constant([[10.0,20.0],[20.0,30.0]])
tfct2.dtype

tf.float32

In [35]:
tfct33 = tf.cast(tfct2,dtype = tf.float16)
tfct33,tfct33.dtype

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[10., 20.],
        [20., 30.]], dtype=float16)>,
 tf.float16)

In [36]:
tff = tf.random.uniform(shape = [50])
tff

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.3239373 , 0.14293587, 0.8532852 , 0.70575154, 0.88140166,
       0.636997  , 0.51391053, 0.3744352 , 0.5556252 , 0.8121394 ,
       0.86350965, 0.988902  , 0.3458749 , 0.491961  , 0.6040399 ,
       0.5849935 , 0.29219425, 0.926075  , 0.8054898 , 0.6672814 ,
       0.50085294, 0.7768234 , 0.1544838 , 0.15235317, 0.19758737,
       0.9595164 , 0.5517888 , 0.61667144, 0.5027071 , 0.36262286,
       0.80654097, 0.75257814, 0.8496189 , 0.7411188 , 0.8327471 ,
       0.33983302, 0.6710669 , 0.28265584, 0.9604517 , 0.46635783,
       0.87321377, 0.47640562, 0.06731021, 0.16252601, 0.61634505,
       0.30944216, 0.4746821 , 0.14509904, 0.62090266, 0.21050632],
      dtype=float32)>

In [37]:
tff[tf.argmax(tff)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.988902>

In [38]:
#squeesing a tensor

In [39]:
G = tf.constant(tf.random.uniform(shape = [50]),shape =(1,2,1,25) )

In [40]:
G,G.shape

(<tf.Tensor: shape=(1, 2, 1, 25), dtype=float32, numpy=
 array([[[[8.6350918e-01, 2.2777784e-01, 4.9710274e-04, 3.0987000e-01,
           9.6228504e-01, 9.4214725e-01, 2.6600361e-02, 8.7819088e-01,
           6.9835663e-02, 2.0925128e-01, 2.5219607e-01, 2.1517539e-01,
           3.4505618e-01, 5.1215518e-01, 5.6767869e-01, 2.6363325e-01,
           6.8963289e-02, 1.4800704e-01, 4.3528283e-01, 4.8242247e-01,
           3.7397027e-02, 8.9928579e-01, 1.8861890e-01, 9.1720724e-01,
           8.1040096e-01]],
 
         [[3.3934915e-01, 7.0534909e-01, 1.4162159e-01, 5.5166960e-02,
           2.2948623e-01, 6.4931846e-01, 5.9234798e-01, 4.3264651e-01,
           4.8711991e-01, 3.2277369e-01, 3.6340833e-01, 6.1080337e-01,
           5.8793414e-01, 5.2271938e-01, 4.4882023e-01, 1.4048910e-01,
           6.1167204e-01, 2.4732447e-01, 4.1959190e-01, 6.3912046e-01,
           1.0907841e-01, 2.3156691e-01, 6.0219145e-01, 2.5743246e-03,
           7.0860374e-01]]]], dtype=float32)>,
 TensorShape([1

In [41]:
G_squeezed = tf.squeeze(G)

In [42]:
G_squeezed.shape,G_squeezed

(TensorShape([2, 25]),
 <tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[8.6350918e-01, 2.2777784e-01, 4.9710274e-04, 3.0987000e-01,
         9.6228504e-01, 9.4214725e-01, 2.6600361e-02, 8.7819088e-01,
         6.9835663e-02, 2.0925128e-01, 2.5219607e-01, 2.1517539e-01,
         3.4505618e-01, 5.1215518e-01, 5.6767869e-01, 2.6363325e-01,
         6.8963289e-02, 1.4800704e-01, 4.3528283e-01, 4.8242247e-01,
         3.7397027e-02, 8.9928579e-01, 1.8861890e-01, 9.1720724e-01,
         8.1040096e-01],
        [3.3934915e-01, 7.0534909e-01, 1.4162159e-01, 5.5166960e-02,
         2.2948623e-01, 6.4931846e-01, 5.9234798e-01, 4.3264651e-01,
         4.8711991e-01, 3.2277369e-01, 3.6340833e-01, 6.1080337e-01,
         5.8793414e-01, 5.2271938e-01, 4.4882023e-01, 1.4048910e-01,
         6.1167204e-01, 2.4732447e-01, 4.1959190e-01, 6.3912046e-01,
         1.0907841e-01, 2.3156691e-01, 6.0219145e-01, 2.5743246e-03,
         7.0860374e-01]], dtype=float32)>)

In [43]:
# tensorflow can interact nicely with numpy arrays
# we have already seen the interoperability converting a numpy array into tensor

In [44]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [45]:
!nvidia-smi 

Sun May 21 08:27:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    29W /  70W |    375MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------