In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('Covid_Dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
#Splitting data intor training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[0 1 1 ... 1 0 0]
 [0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [1 1 1 ... 1 0 0]
 [0 1 1 ... 1 0 0]
 [1 0 1 ... 0 0 0]]
[1 1 1 ... 1 1 1]
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 1 1 ... 1 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 0 1 ... 1 0 0]]
[1 1 1 ... 1 1 1]


In [ ]:
#Logistic Regression
# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

# Predicting a new result
#print(classifier.predict([[1,1,1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,0,0]]))

# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print("Logistic Regression")
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

Logistic Regression
[[ 230   31]
 [  17 1081]]


0.9646799116997793

In [ ]:
# K-Nearest Neighbors (K-NN)
# Training the K-NN model on the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors =11, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

# Predicting a new result for verification
#print(classifier.predict([[1,1,1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,0,0]]))

# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print("K-Nearest Neighbours")
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

K-Nearest Neighbours
[[ 245   16]
 [  21 1077]]


0.9727740986019132

In [ ]:
# Training the Kernel SVM model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting a new result
#print(classifier.predict([[1,1,1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,0,0]]))

# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print("Kernel SVM with rbf")
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

Kernel SVM with rbf
[[ 244   17]
 [  14 1084]]


0.9771891096394407

In [ ]:
# Training the Decision Tree Classification model on the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting a new result
#print(classifier.predict([[1,1,1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,0,0]]))

# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print("Decision Tree Classifier")
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

Decision Tree Classifier
[[ 249   12]
 [  15 1083]]


0.9801324503311258

In [ ]:
#Random Forest Classification
# Training the Random Forest Classification model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting a new result
#print(classifier.predict([[1,1,1,1,1,0,0,0,0,1,1,1,1,0,1,0,1,1,0,0]]))

# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print("Random Forest Classifier")
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


Random Forest Classifier
[[ 244   17]
 [  14 1084]]


0.9771891096394407

In [ ]:
#neural network classifier
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [ ]:
# load dataset
dataframe = pandas.read_csv("C:\\Users\\Kartikay Suri\\Documents\\Code Directory\\Python program\\Covid_Dataset.csv")
dataset = dataframe
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
def create_baseline():
	model = Sequential()
	model.add(Dense(20, input_dim=20, activation='relu'))
	model.add(Dense(1, activation='sigmoid'))
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [ ]:
estimator = KerasClassifier(build_fn=create_baseline, epochs=100, batch_size=5, verbose=0)
kfold = StratifiedKFold(n_splits=2, shuffle=True)
results = cross_val_score(estimator, X_train, y_train, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))