In [ ]:
#tensorflow fundamentals from course
#ignore the double writing

In [ ]:
import tensorflow as tf
print(tf.__version__)
print(tf.__version__)

2.8.2
2.8.2


In [ ]:
#creating the tensor
scalar = tf.constant(7)
print(scalar)
#checking the number of dimesions
scalar.ndim

tf.Tensor(7, shape=(), dtype=int32)


0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10],[7],[8]])
matrix

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[10],
       [ 7],
       [ 8]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix_float = tf.constant([[10.,7.],[7.,10.]],dtype = tf.float16)
matrix_float

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

tensor using tf.Variable


In [ ]:
changable_tensor = tf.Variable([10,7])
static_tensor = tf.constant([10,7])
changable_tensor,static_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#creation of random tensors

In [ ]:
random_tensor = tf.random.Generator.from_seed(43)
random_tensor = random_tensor.normal(shape=(3,3))
random_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ,  0.09988727],
       [-0.50998646, -0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993, -0.3522796 ]], dtype=float32)>

In [ ]:
random_tensor2 = tf.random.Generator.from_seed(43)
random_tensor2 = random_tensor2.normal(shape = (3,3))
random_tensor2
random_tensor2 == random_tensor

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [ ]:
#shuffeling a tensor

In [ ]:
unshuffeled = tf.constant([[10,7],[3,4],[2,5]])
unshuffeled.ndim

2

In [ ]:
#shuffeled value
shuffeled = tf.random.shuffle(unshuffeled)
shuffeled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [1]:
i = 50
def foo():
    i = 100
    return i
 
foo()
print(i)

50
